package es.centroafuera.rolappeame;

public enum Oficio {
    ALQUIMISTA, ASESINO, BAILARINA, BÁRBARO, CAMARERA, CAZADOR, ESCLAVO,
    ESCRIBA, GALENO, GLADIADOR, GRANJERO, HERRERO, JUGLAR, LADRON, MAGO,
    MERCADER, MERCENARIO, NOBLE, PILOTO, PIRATA, SACERDOTE, SOLDADO, VERDUGO
}